config/routes.rb
Rails.application.routes.draw do

  devise_for :user, controllers: {
     sessions:      'public/sessions',
     registrations: 'public/registrations'
  }

  devise_for :admin, controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords',
    registrations: 'admin/registrations'
  }

  namespace :admin do
    resources :stores, only: [:index, :show, :new, :edit, :update, :create, :destroy]
    resources :users, only: [:index, :show, :edit, :update]
    resources :searches, only: [:index]
     resources :reviews, only: [:show,:destroy] do
      resources :review_comments, only: [:destroy]
    end

  end

  scope module: :public do
    root to: 'homes#top'
    resources :stores, only: [:index, :show]
    get 'my_page' => 'users#show'
    get 'unsbscribe' => 'users#create'
    patch 'withdraw' => 'users#destroy'
    resources :users, only: [:edit, :update, :create, :destroy]
    resources :reviews, only: [:new, :show, :edit, :update, :destroy, :create] do
      resources :review_comments, only: [:create, :destroy]
    end
    resources :genres, only: [:index]
  end

  devise_scope :user do
    post 'user/guest_sign_in', to: 'user/sessions#guest_sign_in'
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/atmosphere.rb
class Atmosphere < ApplicationRecord
  has_many :atmosphere_review_relations, dependent: :destroy
  has_many :reviews, through: :atmosphere_review_relations
  has_many :atmosphere_store_relations, dependent: :destroy
  has_many :stores, through: :atmosphere_store_relations
end

app/models/atmosphere_review_relation.rb
class AtmosphereReviewRelation < ApplicationRecord
  belongs_to :review
  belongs_to :atmosphere
end

app/models/atmosphere_store_relation.rb
class AtmosphereStoreRelation < ApplicationRecord
  belongs_to :atmosphere
  belongs_to :store
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :genre_relations, dependent: :destroy
  has_many :stores, through: :genre_relations
end

app/models/genre_relation.rb
class GenreRelation < ApplicationRecord
  belongs_to :store
  belongs_to :genre
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :store
  has_many :review_comments, dependent: :destroy
  has_many :atmosphere_review_relations, dependent: :destroy
  has_many :atmospheres, through: :atmosphere_review_relations
  has_many :scene_review_relations, dependent: :destroy
  has_many :scenes, through: :scene_review_relations

  has_many :review_images, dependent: :destroy
  accepts_attachments_for :review_images, attachment: :image, append: true

  validates :title, presence: true
  validates :review_images_images, presence: true
  validates :scenes, presence: true
  validates :atmospheres, presence: true
  validates :text, presence: true


end

app/models/review_comment.rb
class ReviewComment < ApplicationRecord
  belongs_to :review
  belongs_to :user
  validates :comment, presence: true
end

app/models/review_image.rb
class ReviewImage < ApplicationRecord
  belongs_to :review
  attachment :image
end

app/models/scene.rb
class Scene < ApplicationRecord
  has_many :scene_store_relations, dependent: :destroy
  has_many :stores, through: :scene_store_relations
  has_many :scene_review_relations, dependent: :destroy
  has_many :reviews, through: :scene_review_relations
end

app/models/scene_review_relation.rb
class SceneReviewRelation < ApplicationRecord
  belongs_to :review
  belongs_to :scene
end

app/models/scene_store_relation.rb
class SceneStoreRelation < ApplicationRecord
  belongs_to :scene
  belongs_to :store
end

app/models/store.rb
class Store < ApplicationRecord

  has_many :reviews, dependent: :destroy
  has_many :scene_store_relations, dependent: :destroy
  has_many :scenes, through: :scene_store_relations
  has_many :genre_relations, dependent: :destroy
  has_many :genres, through: :genre_relations
  has_many :atmosphere_store_relations,  dependent: :destroy
  has_many :atmospheres, through: :atmosphere_store_relations

  has_many :store_images, dependent: :destroy
  accepts_attachments_for :store_images, attachment: :image, append: true

  validates :name, presence: true
  validates :store_images_images, presence: true
  validates :explanation, presence: true
  validates :genres, presence: true
  validates :area, presence: true
end

app/models/store_image.rb
class StoreImage < ApplicationRecord
  belongs_to :store
  attachment :image
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_relations, dependent: :destroy
  has_many :store, through: :tag_relations
end

app/models/tag_relation.rb
class TagRelation < ApplicationRecord
  belongs_to :store
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.guest
    find_or_create_by!(email: 'guest2@example.com',first_name: 'ゲスト', last_name: ' ゲスト', first_name_kana: 'ゲスト ', last_name_kana: 'ゲスト', nickname: 'ゲスト') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def active_for_authentication?#退会した人をログインできなくしてる。
    super && (is_active == true)
  end

  has_many :reviews, dependent: :destroy
  has_many :review_comments, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :email, presence: true
  validates :nickname, presence: true

end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
   before_action :authenticate_admin!

  def show
     @review = Review.find(params[:id])
     @review_comment = ReviewComment.new
  end

  def destroy
    @review = Review.find(params[:id])
    @store = @review.store
    @review.destroy
    redirect_to admin_store_path(@store.id)
  end


  private

  def review_params
    params.require(:review).permit(:name, :title, :store_id,  :text, review_images_images: [], genre_ids: [], scene_ids: [], atmosphere_ids: [])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :nickname])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/reviews/show.html.erb
<div class="container">
  <h2>レビュー詳細</h2>
  <p class="text-right"><%= link_to "レビュー削除", admin_review_path(@review), method: :delete, class: "btn btn-danger" %></p>
  <table>
    <tr>
      <td style="display: inline-block;">
        <% @review.review_images.each do |image| %>
          <%= attachment_image_tag image, :image, :fill, 150, 150 %>
        <% end %>
      </td>
    </tr>
    <tr>
      <td class="font-weight-bold">タイトル</td>
      <td style="height: 50px;"><%= @review.title %></td>
    </tr>
    <tr>
      <td class="font-weight-bold">利用シーン</td>
      <td style="height: 50px;">
        <% @review.scenes.each do |scene| %>
          <%= scene.name %>
        <% end %>
      </td>
    </tr>
    <tr>
      <td class="font-weight-bold">雰囲気</td>
      <td style="height: 50px;">
        <% @review.atmospheres.each do |atmosphere| %>
          <%= atmosphere.name %>
        <% end %>
      </td>
    </tr>
    <tr>
      <td class="font-weight-bold">レビュー</td>
      <td style="height: 50px;"><%= safe_join(@review.text.split("\n"),tag(:br)) %></td>
    </tr>
  </table>
  <div class="row">
    <% @review.review_comments.each do |review_comment| %>
    <div class="col-sm-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">コメント件数：<%= @review.review_comments.count %></h5>
          <h5 class="card-title">投稿者：<%= review_comment.user.nickname %> <%= review_comment.created_at.strftime('%Y/%m/%d') %></h5>
          <p class="card-text", style="display: inline-block;">コメント：<%= review_comment.comment %></p>
        </div>
      </div>
    </div>
  </div>
  <div style="padding: 1%;"><%= link_to "コメントを削除", admin_review_review_comment_path(review_comment.review, review_comment), method: :delete, class: "btn btn-danger"  %></div>
  <% end %>
</div>