config/routes.rb
Rails.application.routes.draw do

  devise_for :user, controllers: {
     sessions:      'public/sessions',
     registrations: 'public/registrations'
  }

  devise_for :admin, controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords',
    registrations: 'admin/registrations'
  }

  namespace :admin do
    resources :stores, only: [:index, :show, :new, :edit, :update, :create, :destroy]
    resources :users, only: [:index, :show, :edit, :update]
    resources :searches, only: [:index]
     resources :reviews, only: [:show,:destroy] do
      resources :review_comments, only: [:destroy]
    end

  end

  scope module: :public do
    root to: 'homes#top'
    resources :stores, only: [:index, :show]
    get 'my_page' => 'users#show'
    get 'unsbscribe' => 'users#create'
    patch 'withdraw' => 'users#destroy'
    resources :users, only: [:edit, :update, :create, :destroy]
    resources :reviews, only: [:new, :show, :edit, :update, :destroy, :create] do
      resources :review_comments, only: [:create, :destroy]
    end
    resources :genres, only: [:index]
  end

  devise_scope :user do
    post 'user/guest_sign_in', to: 'user/sessions#guest_sign_in'
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/atmosphere.rb
class Atmosphere < ApplicationRecord
  has_many :atmosphere_review_relations, dependent: :destroy
  has_many :reviews, through: :atmosphere_review_relations
  has_many :atmosphere_store_relations, dependent: :destroy
  has_many :stores, through: :atmosphere_store_relations
end

app/models/atmosphere_review_relation.rb
class AtmosphereReviewRelation < ApplicationRecord
  belongs_to :review
  belongs_to :atmosphere
end

app/models/atmosphere_store_relation.rb
class AtmosphereStoreRelation < ApplicationRecord
  belongs_to :atmosphere
  belongs_to :store
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :genre_relations, dependent: :destroy
  has_many :stores, through: :genre_relations
end

app/models/genre_relation.rb
class GenreRelation < ApplicationRecord
  belongs_to :store
  belongs_to :genre
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :store
  has_many :review_comments, dependent: :destroy
  has_many :atmosphere_review_relations, dependent: :destroy
  has_many :atmospheres, through: :atmosphere_review_relations
  has_many :scene_review_relations, dependent: :destroy
  has_many :scenes, through: :scene_review_relations

  has_many :review_images, dependent: :destroy
  accepts_attachments_for :review_images, attachment: :image, append: true

  validates :title, presence: true
  validates :review_images_images, presence: true
  validates :scenes, presence: true
  validates :atmospheres, presence: true
  validates :text, presence: true


end

app/models/review_comment.rb
class ReviewComment < ApplicationRecord
  belongs_to :review
  belongs_to :user
  validates :comment, presence: true
end

app/models/review_image.rb
class ReviewImage < ApplicationRecord
  belongs_to :review
  attachment :image
end

app/models/scene.rb
class Scene < ApplicationRecord
  has_many :scene_store_relations, dependent: :destroy
  has_many :stores, through: :scene_store_relations
  has_many :scene_review_relations, dependent: :destroy
  has_many :reviews, through: :scene_review_relations
end

app/models/scene_review_relation.rb
class SceneReviewRelation < ApplicationRecord
  belongs_to :review
  belongs_to :scene
end

app/models/scene_store_relation.rb
class SceneStoreRelation < ApplicationRecord
  belongs_to :scene
  belongs_to :store
end

app/models/store.rb
class Store < ApplicationRecord

  has_many :reviews, dependent: :destroy
  has_many :scene_store_relations, dependent: :destroy
  has_many :scenes, through: :scene_store_relations
  has_many :genre_relations, dependent: :destroy
  has_many :genres, through: :genre_relations
  has_many :atmosphere_store_relations,  dependent: :destroy
  has_many :atmospheres, through: :atmosphere_store_relations

  has_many :store_images, dependent: :destroy
  accepts_attachments_for :store_images, attachment: :image, append: true

  validates :name, presence: true
  validates :store_images_images, presence: true
  validates :explanation, presence: true
  validates :genres, presence: true
  validates :area, presence: true
end

app/models/store_image.rb
class StoreImage < ApplicationRecord
  belongs_to :store
  attachment :image
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_relations, dependent: :destroy
  has_many :store, through: :tag_relations
end

app/models/tag_relation.rb
class TagRelation < ApplicationRecord
  belongs_to :store
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.guest
    find_or_create_by!(email: 'guest2@example.com',first_name: 'ゲスト', last_name: ' ゲスト', first_name_kana: 'ゲスト ', last_name_kana: 'ゲスト', nickname: 'ゲスト') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def active_for_authentication?#退会した人をログインできなくしてる。
    super && (is_active == true)
  end

  has_many :reviews, dependent: :destroy
  has_many :review_comments, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :email, presence: true
  validates :nickname, presence: true

end

app/controllers/admin/stores_controller.rb
class Admin::StoresController < ApplicationController
   before_action :authenticate_admin!

  def index
    @stores = Store.page(params[:page]).per(4)
    @search = Store.ransack(params[:q])
    @store_search = @search.result(distinct: true).page(params[:page]).per(4)


    # if params[:q].nil? || (params[:q][:name_cont].blank? && params[:q][:area_cont].blank?)
    #   #検索されていないとき
    #   @stores = Store.page(params[:page]).per(5)
    # else

    #   name = []
    #   unless params[:q][:name_cont].blank?
    #     #name検索されたとき
    #     name += Store.ransack(name_cont: params[:q][:name_cont]).result(distinct: true).pluck(:name)
    #   end
    #   unless params[:q][:area_cont].blank?
    #     #area検索されたとき
    #     name += Store.ransack(area_cont: params[:q][:area_cont]).result(distinct: true).pluck(:name)
    #   end
    #   #検索結果から重複を取り除いて取得する
    #   @stores = Store.where(name: name.uniq).page(params[:page]).per(5)
    # end

    # @search = Store.ransack(params[:q])

  end

  def create
    @store = Store.new(store_params)
    if @store.save!
      redirect_to admin_store_path(@store.id)
    else
      render :new
    end
  end

  def new
    @store = Store.new
  end

  def show
    @store = Store.find(params[:id])
    @reviews = @store.reviews.page(params[:page]).per(4)
  end

  def edit
    @store = Store.find(params[:id])
  end

  def destroy
    @store = Store.find(params[:id])
    @store.destroy
    redirect_to admin_stores_path
  end

  def update
    @store= Store.find(params[:id])
    image_params = params[:store][:store_images_images]
    @store.store_images.destroy_all if image_params.dig(1).present?#if文ははstore＿imageに２番目以降に画像があったら今ある画像をを削除
    if @store.update(store_params)
      redirect_to admin_store_path(@store.id)
    else
      render :edit
    end
  end

  private

  def store_params
    params.require(:store).permit(:name, :genre_id, :scene_id, :atmosphere_id, :explanation, :area, store_images_images: [], genre_ids: [])
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :nickname])
  end
end

app/helpers/admin/stores_helper.rb
module Admin::StoresHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/stores/edit.html.erb
<div class="container">
  <b style="margin-left: 50px; margin-top: 100px; font-size: xx-large;">店舗情報編集</b>
  <p class="text-right"><%= link_to"店舗削除", admin_store_path(@store), method: :delete, class: "btn btn-danger" %></p>
  <% if @store.errors.any? %>
  <%= @store.errors.count %>件のエラーが発生しました
    <% @store.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>
  <%= form_with model: @store,url: admin_store_path, local:true do |f| %>
  <div style="display: inline-block; margin-left: 250px;">
    <div class="col", style="margin-top: 50px;">
      <p><%= f.label :store_images_images, '店舗画像' %></p>
      <p><%= f.attachment_field :store_images_images, multiple: true  %></p>
    </div>
    <div class="col">
      <p><%= f.label :area, "地域(都道府県)" %></p>
      <p><%= f.text_field :area, size: "40x20" %></p>
    </div>
    <div class="col">
      <p><%= f.label :genre, "ジャンル" %></p>
      <p>
        <%= f.collection_check_boxes(:genre_ids, Genre.all, :id, :name) do |genre| %>
          <%= genre.label do %>
            <%= genre.check_box %>
            <%= genre.text %>
          <% end %>
        <% end %>
      </p>
    </div>
    <div class="col">
      <p><%= f.label :name, "店舗名" %></p>
      <p><%= f.text_field :name, size: "40x20" %></p><br>
    </div>
    <div class="col">
      <p><%= f.label :explanation, "店舗説明" %></p>
      <p><%= f.text_area :explanation, size: "50x5" %></p><br>
    </div>
    <div style="margin-left: 200px;">
      <%= f.submit '情報を変更' , class: "btn btn-success" %>
    </div>
    <% end %>
  </div>
</div>

app/views/admin/stores/index.html.erb
<div class="container">
  <b style="margin-left: 100px; margin-top: 100px; font-size: xx-large;">店舗一覧</b>
  <p class="text-right"><%= link_to"新規登録", new_admin_store_path, class: "btn btn-success" %></p>
  <div class="store_explanation">
    <div>
      <b style="margin-left: 100px; margin-top: 100px; font-size: large;">検索</b>
      <%= search_form_for @search, url:  admin_stores_path do |f| %>
      <%= f.label :name, "店舗名" %>
      <%= f.search_field :name_cont %>
      <%= f.label :area, "地域(都道府県)" %>
      <%= f.search_field :area_cont %>
      <%= f.submit "検索", class: "btn btn-success"  %>
       <% end %>
    </div>
    <table style="margin-top: 50px; text-align: center;"　class="table table-success table-striped">
      <tr class="border-top border-bottom font-weight-bold", style="text-align: center;">
        <th>店舗画像</th>
        <th>店舗名</th>
        <th>地域</th>
      </tr>
      <% @store_search.each do |store| %>
      <%# @stores.each do |store| %>
      <tr class="border-top border-bottom">
        <td style="width: 300px;">
          <% if store.store_images.present? %>
            <% store.store_images.first(1).each do |image| %>
            <%= attachment_image_tag image, :image, :fill, 200, 200 %>
            <% end %>
          <% end %>
        </td>
        <td style="width: 300px;">
          <%= link_to admin_store_path(store.id) do %>
            <%= store.name %>
          <% end %>
        </td>
        <td style="width: 300px;">
          <%= link_to admin_store_path(store.id) do %>
            <%= store.area %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
  <div style="margin-left: 450px; margin-top: 50px;">
    <%= paginate @stores %>
  </div>
</div>

app/views/admin/stores/new.html.erb
<div class="container">
  <b style="margin-left: 50px; margin-top: 100px; font-size: xx-large;">店舗新規登録</b>
  <%= form_with model: @store,url: admin_stores_path, local:true do |f| %>
  <div style="display: inline-block; margin-left: 250px;">
    <div class="col">
      <% if @store.errors.any? %>
        <div><%= @store.errors.count %>件のエラーが発生しました</div>
          <% @store.errors.full_messages.each do |message| %>
          <P><%= message %></P>
        <% end %>
      <% end %>
    </div>
    <div class="col", style="margin-top: 50px;">
      <p><%= f.label :store_images_images, '店舗画像' %></p>
      <p><%= f.attachment_field :store_images_images, multiple: true  %></p>
    </div>
    <div class="col">
      <p><%= f.label :area, "地域(都道府県)" %></p>
      <p><%= f.text_field :area, size: "40x20" %></p>
    </div>
    <div class="col">
      <p><%= f.label :genre, "ジャンル" %></p>
      <p>
        <%= f.collection_check_boxes(:genre_ids, Genre.all, :id, :name) do |genre| %>
          <%= genre.label do %>
            <%= genre.check_box %>
            <%= genre.text %>
          <% end %>
        <% end %>
      </p>
    </div>
    <div class="col">
      <p><%= f.label :name, "店舗名" %></p>
      <p><%= f.text_field :name, size: "40x20" %></p><br>
    </div>
    <div class="col">
      <p><%= f.label :explanation, "店舗説明" %></p>
      <p><%= f.text_area :explanation, size: "50x5" %></p><br>
    </div>
    <div style="margin-left: 200px;">
      <%= f.submit '新規投稿' , class: "btn btn-success" %>
    </div>
    <% end %>
  </div>
</div>

app/views/admin/stores/show.html.erb
<div class="container">
  <b style="margin-left: 100px; margin-top: 100px; font-size: xx-large;">店舗詳細</b>
  <p class="text-right"><%= link_to"店舗情報を変更", edit_admin_store_path, class: "btn btn-success" %></p>
  <div style="display: inline-block; margin-left: 100px;">
    <% @store.store_images.each do |image| %>
      <%= attachment_image_tag image, :image, :fill, 200, 200 %>
    <% end %>
  </div>
  <table style="width: 400px; text-align-last: left; margin-left: 100px; margin-bottom: 50px;">
    <tr>
      <td style="height: 50px;" class="font-weight-bold">店舗名</td>
      <td style="height: 50px; margin-left: 44px;"><%= @store.name %></td>
    </tr>
    <tr>
      <td style="height: 50px;" class="font-weight-bold">ジャンル</td>
      <td style="height: 50px; margin-left: 44px;">
        <% @store.genres.each do |genre| %>
          <%= genre.name %>
        <% end %>
      </td>
    </tr>
    <tr>
      <td style="height: 50px;" class="font-weight-bold">地域</td>
      <td style="height: 50px; margin-left: 44px;"><%= @store.area %></td>
    </tr>
    <tr>
      <td style="height: 50px;" class="font-weight-bold">店舗詳細</td>
      <td style="height: 50px; margin-left: 30px;"><%= safe_join(@store.explanation.split("\n"),tag(:br)) %></td>
    </tr>
  </table>
  <b style="font-size: large;">投稿レビュー</b><br>
  <div class="row">
  <% @reviews.each do |review| %>
    <div class="card col-lg-6 col-12">
    <%= link_to admin_review_path(review) do %>
      <div class="row g-0">
        <div class="col-md-4">
          <% review.review_images.first(1).each do |image| %>
            <%= attachment_image_tag image, :image, :fill, 200, 200 %>
          <% end %>
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <div class="row">
                  <div class="col-md-4">
                    <span class="font-weight-bold">タイトル</span>
                  </div>
                  <div class="col-md-8">
                    <span style="text-align: right;"><%=review.title%></span>
                  </div>
                </div>
              </li>
              <li class="list-group-item">
                <div class="row">
                  <div class="col-md-4">
                    <span class="font-weight-bold">シーン</span>
                  </div>
                  <div class="col-md-8">
                    <span style="text-align: right;">
                      <% review.scenes.each do |scene| %>
                      <%= scene.name %>
                      <% end %>
                    </span>
                  </div>
                </div>
              </li>
              <li class="list-group-item">
                <div class="row">
                  <div class="col-md-4">
                    <span class="font-weight-bold">雰囲気</span>
                  </div>
                  <div class="col-md-8">
                    <span style="text-align: right;">
                      <% review.atmospheres.each do |atmosphere| %>
                        <%= atmosphere.name %>
                      <% end %>
                    </span>
                  </div>
                </div>
              </li>
              <li class="list-group-item">
                <div class="row">
                  <div class="col-md-4">
                    <span class="font-weight-bold">レビュー内容</span>
                  </div>
                  <div class="col-md-8">
                    <span style="text-align: right;"><%= review.text %></span>
                  </div>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
    </div>
  <% end %>
  </div>
  <div style="margin-left: 450px; margin-top: 50px;">
    <%= paginate @reviews %>
  </div>
</div>