config/routes.rb
Rails.application.routes.draw do

  devise_for :user, controllers: {
     sessions:      'public/sessions',
     registrations: 'public/registrations'
  }

  devise_for :admin, controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords',
    registrations: 'admin/registrations'
  }

  namespace :admin do
    resources :stores, only: [:index, :show, :new, :edit, :update, :create, :destroy]
    resources :users, only: [:index, :show, :edit, :update]
    resources :searches, only: [:index]
     resources :reviews, only: [:show,:destroy] do
      resources :review_comments, only: [:destroy]
    end

  end

  scope module: :public do
    root to: 'homes#top'
    resources :stores, only: [:index, :show]
    get 'my_page' => 'users#show'
    get 'unsbscribe' => 'users#create'
    patch 'withdraw' => 'users#destroy'
    resources :users, only: [:edit, :update, :create, :destroy]
    resources :reviews, only: [:new, :show, :edit, :update, :destroy, :create] do
      resources :review_comments, only: [:create, :destroy]
    end
    resources :genres, only: [:index]
  end

  devise_scope :user do
    post 'user/guest_sign_in', to: 'user/sessions#guest_sign_in'
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/atmosphere.rb
class Atmosphere < ApplicationRecord
  has_many :atmosphere_review_relations, dependent: :destroy
  has_many :reviews, through: :atmosphere_review_relations
  has_many :atmosphere_store_relations, dependent: :destroy
  has_many :stores, through: :atmosphere_store_relations
end

app/models/atmosphere_review_relation.rb
class AtmosphereReviewRelation < ApplicationRecord
  belongs_to :review
  belongs_to :atmosphere
end

app/models/atmosphere_store_relation.rb
class AtmosphereStoreRelation < ApplicationRecord
  belongs_to :atmosphere
  belongs_to :store
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :genre_relations, dependent: :destroy
  has_many :stores, through: :genre_relations
end

app/models/genre_relation.rb
class GenreRelation < ApplicationRecord
  belongs_to :store
  belongs_to :genre
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :store
  has_many :review_comments, dependent: :destroy
  has_many :atmosphere_review_relations, dependent: :destroy
  has_many :atmospheres, through: :atmosphere_review_relations
  has_many :scene_review_relations, dependent: :destroy
  has_many :scenes, through: :scene_review_relations

  has_many :review_images, dependent: :destroy
  accepts_attachments_for :review_images, attachment: :image, append: true

  validates :title, presence: true
  validates :review_images_images, presence: true
  validates :scenes, presence: true
  validates :atmospheres, presence: true
  validates :text, presence: true


end

app/models/review_comment.rb
class ReviewComment < ApplicationRecord
  belongs_to :review
  belongs_to :user
  validates :comment, presence: true
end

app/models/review_image.rb
class ReviewImage < ApplicationRecord
  belongs_to :review
  attachment :image
end

app/models/scene.rb
class Scene < ApplicationRecord
  has_many :scene_store_relations, dependent: :destroy
  has_many :stores, through: :scene_store_relations
  has_many :scene_review_relations, dependent: :destroy
  has_many :reviews, through: :scene_review_relations
end

app/models/scene_review_relation.rb
class SceneReviewRelation < ApplicationRecord
  belongs_to :review
  belongs_to :scene
end

app/models/scene_store_relation.rb
class SceneStoreRelation < ApplicationRecord
  belongs_to :scene
  belongs_to :store
end

app/models/store.rb
class Store < ApplicationRecord

  has_many :reviews, dependent: :destroy
  has_many :scene_store_relations, dependent: :destroy
  has_many :scenes, through: :scene_store_relations
  has_many :genre_relations, dependent: :destroy
  has_many :genres, through: :genre_relations
  has_many :atmosphere_store_relations,  dependent: :destroy
  has_many :atmospheres, through: :atmosphere_store_relations

  has_many :store_images, dependent: :destroy
  accepts_attachments_for :store_images, attachment: :image, append: true

  validates :name, presence: true
  validates :store_images_images, presence: true
  validates :explanation, presence: true
  validates :genres, presence: true
  validates :area, presence: true
end

app/models/store_image.rb
class StoreImage < ApplicationRecord
  belongs_to :store
  attachment :image
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_relations, dependent: :destroy
  has_many :store, through: :tag_relations
end

app/models/tag_relation.rb
class TagRelation < ApplicationRecord
  belongs_to :store
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.guest
    find_or_create_by!(email: 'guest2@example.com',first_name: 'ゲスト', last_name: ' ゲスト', first_name_kana: 'ゲスト ', last_name_kana: 'ゲスト', nickname: 'ゲスト') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def active_for_authentication?#退会した人をログインできなくしてる。
    super && (is_active == true)
  end

  has_many :reviews, dependent: :destroy
  has_many :review_comments, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :email, presence: true
  validates :nickname, presence: true

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = User.all
    @users = User.page(params[:page]).per(4)
  end

  def show
    @user = User.find(params[:id])
    @name = @user.first_name + @user.last_name
    @name_kana = @user.first_name_kana + @user.last_name_kana
  end

  def edit
    @user = User.find(params[:id])
    @name = @user.first_name + @user.last_name
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path
    else
      render :edit
    end
  end

  private

  def user_params
     params.require(:user).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :nickname, :email, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :nickname])
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_in_path_for(resource)
    my_page_path(resource)
  end
  def after_sign_out_path_for(resource)
    root_path(resource)
  end

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to stores_path, notice: 'ゲストユーザーでログインしました。'
  end

  def reject_user
    @user = current_user
      if @user
        if @user.valid_password?(params[:customer][:password]) &&  (@user.active_for_authentication? == true)
        redirect_to new_user_registration
        end
      end
  end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/edit.html.erb
<div class="container-fluid">
	  <div class="row h-50">
	    <div class= "col-md-6 offset-md-3 mt-5">
	      <div>
          <span class="h2 mr-5", style="margin-top: 5%;"><%= @user.first_name + @user.last_name %>さんの会員情報編集<span>
        </div>
        <% if @user.errors.any? %>
          <div><%= @user.errors.count %>件のエラーが発生しました</div>
          <% @user.errors.full_messages.each do |message| %>
            <p><%= message %></p>
          <% end %>
        <% end %>
        <div class="table-responsive-sm">
        <%= form_with model: @user,url: admin_user_path, local:true do |f| %>
        <table class="table">
          <tbody class="table table-borderless">
            <tr>
              <td>会員ID</td>
              <td><%= @user.id %></td>
            </tr>
            <tr>
              <td>氏名</td>
              <td><%= f.text_field :first_name, autofocus: true %></td>
              <td><%= f.text_field :last_name, autofocus: true %></td>
            </tr>
            <tr>
              <td>フリガナ(セイ)</td>
              <td><%= f.text_field :first_name_kana, autofocus: true %></td>
              <td><%= f.text_field :last_name_kana, autofocus: true %></td>
            </tr>
            <tr>
              <td>ニックネーム</td>
              <td><%= f.text_field :nickname, autofocus: true %></td>
            </tr>
              <td>メールアドレス</td>
              <td><%= f.email_field :email, autofocus: true, autocomplete: "email" %> </td>
            </tr>
            <tr>
              <th>会員ステータス</th>
              <td>
                <%= f.radio_button :is_active, true %>
                <%= f.label :is_active, "有効" %>
                <%= f.radio_button :is_active, false %>
                <%= f.label :is_active, "退会" %>
              </td>
            </tr>
            <tr>
              <td></td>
              <td><%= f.submit "変更を保存", class: "btn btn-success"%></td>
            </tr>
          </tbody>
        </table>
        <% end %>
       </div>
      </div>
    </div>
  </div>

app/views/admin/users/index.html.erb
<div class="container">
  <b style="margin-left: 100px; margin-top: 100px; font-size: xx-large;">会員一覧</b>
  <div>
    <table style="margin-top: 30px; width: -webkit-fill-available;;">
      <tr class="border-top border-bottom">
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>会員ステータス</th>
      </tr>
      <% @users.each do |user| %>
      <tr style="height: 50px; text-underline: auto;">
        <td><%= user.id %></td>
        <td>
          <%= link_to admin_user_path(user.id) do %>
          <%= user.first_name + user.last_name %>
          <% end %>
        </td>
        <td>
          <%= user.email %>
        </td>
        <% if user.is_active %>
        <td  class="font-weight-bold" style="color: #28a745;">有効</td>
        <% else %>
        <td  class="font-weight-bold" style="color: #dc3545;">退会</td>
        <% end %>
      </tr>
      <% end %>
    </table>
    <div style="margin-left: 450px; margin-top: 50px;">
     <%= paginate @users %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <p class="h4", style="margin-top: 5%;"><%= @name %>さんの会員詳細</p>
  <table class="table table-borderless"  style="margin: 3%; width: 50%; margin-left: 25%;">
    <tr>
      <td>会員ID</td>
      <td><%= @user.id %></td>
    </tr>
    <tr>
      <td>氏名</td>
      <td><%= @name %></td>
    </tr>
    <tr>
      <td>フリガナ</td>
      <td><%= @name_kana %></td>
    </tr>
    <tr>
      <td>ニックネーム</td>
      <td><%= @user.nickname %></td>
    </tr>
    <tr>
      <td>メールアドレス</td>
      <td><%= @user.email %></td>
    </tr>
    <tr>
      <td>会員ステータス</td>
      <% if @user.is_active %>
      <td  class="font-weight-bold" style="color: #28a745;">有効</td>
      <% else %>
      <td  class="font-weight-bold" style="color: #dc3545;">退会</td>
      <% end %>
    </tr>
  </table>
  <div style="margin-left: 50%;"><%= link_to "編集する", edit_admin_user_path, class: "btn btn-success" %></div>
</div>