config/routes.rb
Rails.application.routes.draw do

  devise_for :user, controllers: {
     sessions:      'public/sessions',
     registrations: 'public/registrations'
  }

  devise_for :admin, controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords',
    registrations: 'admin/registrations'
  }

  namespace :admin do
    resources :stores, only: [:index, :show, :new, :edit, :update, :create, :destroy]
    resources :users, only: [:index, :show, :edit, :update]
    resources :searches, only: [:index]
     resources :reviews, only: [:show,:destroy] do
      resources :review_comments, only: [:destroy]
    end

  end

  scope module: :public do
    root to: 'homes#top'
    resources :stores, only: [:index, :show]
    get 'my_page' => 'users#show'
    get 'unsbscribe' => 'users#create'
    patch 'withdraw' => 'users#destroy'
    resources :users, only: [:edit, :update, :create, :destroy]
    resources :reviews, only: [:new, :show, :edit, :update, :destroy, :create] do
      resources :review_comments, only: [:create, :destroy]
    end
    resources :genres, only: [:index]
  end

  devise_scope :user do
    post 'user/guest_sign_in', to: 'user/sessions#guest_sign_in'
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/atmosphere.rb
class Atmosphere < ApplicationRecord
  has_many :atmosphere_review_relations, dependent: :destroy
  has_many :reviews, through: :atmosphere_review_relations
  has_many :atmosphere_store_relations, dependent: :destroy
  has_many :stores, through: :atmosphere_store_relations
end

app/models/atmosphere_review_relation.rb
class AtmosphereReviewRelation < ApplicationRecord
  belongs_to :review
  belongs_to :atmosphere
end

app/models/atmosphere_store_relation.rb
class AtmosphereStoreRelation < ApplicationRecord
  belongs_to :atmosphere
  belongs_to :store
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :genre_relations, dependent: :destroy
  has_many :stores, through: :genre_relations
end

app/models/genre_relation.rb
class GenreRelation < ApplicationRecord
  belongs_to :store
  belongs_to :genre
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :store
  has_many :review_comments, dependent: :destroy
  has_many :atmosphere_review_relations, dependent: :destroy
  has_many :atmospheres, through: :atmosphere_review_relations
  has_many :scene_review_relations, dependent: :destroy
  has_many :scenes, through: :scene_review_relations

  has_many :review_images, dependent: :destroy
  accepts_attachments_for :review_images, attachment: :image, append: true

  validates :title, presence: true
  validates :review_images_images, presence: true
  validates :scenes, presence: true
  validates :atmospheres, presence: true
  validates :text, presence: true


end

app/models/review_comment.rb
class ReviewComment < ApplicationRecord
  belongs_to :review
  belongs_to :user
  validates :comment, presence: true
end

app/models/review_image.rb
class ReviewImage < ApplicationRecord
  belongs_to :review
  attachment :image
end

app/models/scene.rb
class Scene < ApplicationRecord
  has_many :scene_store_relations, dependent: :destroy
  has_many :stores, through: :scene_store_relations
  has_many :scene_review_relations, dependent: :destroy
  has_many :reviews, through: :scene_review_relations
end

app/models/scene_review_relation.rb
class SceneReviewRelation < ApplicationRecord
  belongs_to :review
  belongs_to :scene
end

app/models/scene_store_relation.rb
class SceneStoreRelation < ApplicationRecord
  belongs_to :scene
  belongs_to :store
end

app/models/store.rb
class Store < ApplicationRecord

  has_many :reviews, dependent: :destroy
  has_many :scene_store_relations, dependent: :destroy
  has_many :scenes, through: :scene_store_relations
  has_many :genre_relations, dependent: :destroy
  has_many :genres, through: :genre_relations
  has_many :atmosphere_store_relations,  dependent: :destroy
  has_many :atmospheres, through: :atmosphere_store_relations

  has_many :store_images, dependent: :destroy
  accepts_attachments_for :store_images, attachment: :image, append: true

  validates :name, presence: true
  validates :store_images_images, presence: true
  validates :explanation, presence: true
  validates :genres, presence: true
  validates :area, presence: true
end

app/models/store_image.rb
class StoreImage < ApplicationRecord
  belongs_to :store
  attachment :image
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_relations, dependent: :destroy
  has_many :store, through: :tag_relations
end

app/models/tag_relation.rb
class TagRelation < ApplicationRecord
  belongs_to :store
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.guest
    find_or_create_by!(email: 'guest2@example.com',first_name: 'ゲスト', last_name: ' ゲスト', first_name_kana: 'ゲスト ', last_name_kana: 'ゲスト', nickname: 'ゲスト') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def active_for_authentication?#退会した人をログインできなくしてる。
    super && (is_active == true)
  end

  has_many :reviews, dependent: :destroy
  has_many :review_comments, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :email, presence: true
  validates :nickname, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :nickname])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yummy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header class="head">
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #FCBC3D;">
      <a class="navbar-brand" href="/", style="font-family: HGP行書体;"><h2>Yummy</h2></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto ">
          <% if user_signed_in? %>
          <% if current_user.email == "guest2@example.com" %>
          <% else%>
          <li class="nav-item active mr-2 mb-2">
            <%= link_to "マイページ", my_page_path, class: "btn btn-success" %>
          </li>
          <% end %>
          <li class="nav-item active mr-2 mb-2">
            <%= link_to "店舗一覧", stores_path, class: "btn btn-primary" %>
          </li>
          <li class="nav-item active mr-2 mb-2">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
          </li>
          <% elsif admin_signed_in? %>
          <li class="nav-item active mr-2 mb-2">
            <%= link_to "店舗一覧", admin_stores_path, class: "btn btn-primary" %>
          </li>
          <li class="nav-item active mr-2 mb-2">
            <%= link_to "顧客一覧", admin_users_path, class: "btn btn-secondary" %>
          </li>
          <li class="nav-item active mr-2 mb-2">
           <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-danger" %>
          </li>
          <% else %>
          <li class="nav-item active mr-2 mb-2">
            <%= link_to "新規登録", new_user_registration_path, class: "btn btn-info" %>
          </li>
          <li class="nav-item active mr-2 mb-2">
            <%= link_to "ログイン", new_user_session_path, class: "btn btn-success" %>
          </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </header>
  <footer class="footer" style="background-color: beige; width:100%; height: 50px;">
  </footer>
</html>